#pragma once

#define STR_ABOUT_WINDOW_TITLE          ICON_MDI_INFORMATION " About"
#define STR_METRICS_WINDOW_TITLE        ICON_MDI_CHART_BAR " Dear ImGui Metrics"
#define STR_MENU_ITEM_APPLICATION       "Application"
#define STR_MENU_ITEM_SHOW_WORKSPACE    ICON_MDI_DESKTOP_MAC_DASHBOARD " Show Workspace"
#define STR_MENU_ITEM_THEME             ICON_MDI_PALETTE " Theme"
#define STR_MENU_ITEM_STYLE             "Style"
#define STR_MENU_ITEM_FONT              "Font"
#define STR_MENU_ITEM_CONFIGURATION     ICON_MDI_SETTINGS " Configuration"
#define STR_MENU_ITEM_MOUSE_EMULATION   ICON_MDI_CURSOR_DEFAULT " Mouse emulation"
#define STR_MENU_ITEM_TOUCH_ENABLED     ICON_MDI_HAND_POINTING_DOWN " Enable touch"
#define STR_MENU_ITEM_HELP              "Help"
#define STR_MENU_ITEM_QUIT              ICON_MDI_LOGOUT " Quit"

#define STR_DECODER                     "Decoder"
#define STR_READY                       "Ready"
#define STR_NAME                        "Name"
#define STR_SIZE                        "Size"
#define STR_LOADING                     "Loading"
#define STR_DISK_INFORMATION            "Disk Information"
#define STR_TITLE                       "Title"
#define STR_RIPPER                      "Ripper"
#define STR_CONVERTER                   "Converter"
#define STR_COPYRIGHT                   "Copyright"
#define STR_TRACK_COUNT                 "Track count"
#define STR_TOTAL_DURATION              "Total duration"
#define STR_TRACK_INFORMATION           "Track Information"
#define STR_AUTHOR                      "Author"
#define STR_TRACK_NUMBER                "Track number"
#define STR_PLAY_TIME                   "Play time"
#define STR_DURATION                    "Duration"
#define STR_COMMENTS                    "Comments"
#define STR_TRACK_NO_TITLE              "n/a (No title provided)"
#define STR_PAUSED                      "Paused."
#define STR_PLAYING                     "Playing..."
#define STR_BUTTON_PLAY                 ICON_MDI_PLAY " PLAY"
#define STR_BUTTON_PAUSE                ICON_MDI_PAUSE " PAUSE"
#define STR_BUTTON_STOP                 ICON_MDI_STOP " STOP"
#define STR_BUTTON_BACK                 ICON_MDI_SKIP_PREVIOUS " BACK"
#define STR_BUTTON_NEXT                 ICON_MDI_SKIP_NEXT " NEXT"
#define STR_MOUNT_POINTS                "Mount points"
#define STR_PLAYING_S                   ICON_MDI_MUSIC " Playing: %s"


// Errors

#define STR_ERROR_NAVIGATE_THREAD_WORKING   "Trying to navigate while file system thread is working."
#define STR_ERROR_NO_FILESYSTEM             "No file system to work with"
#define STR_ERROR_FILESYSTEM_THREAD_START   "Unable to start file system thread"
#define STR_ERROR_OPEN_AUDIO_DEVICE         "Couldn't open audio device"
#define STR_ERROR_NO_DECODER_CAN_HANDLE     "No decoder can handle"
#define STR_ERROR_CANT_OPEN_FILE            "Can't open file"
#define STR_ERROR_CANT_PLAY_SONG            "can't play song"
#define STR_ERROR_DECODER_ERROR             "Decoder error"
#define STR_ERROR_LOADING_FILE              "Error loading file"
